version: "3.9"

services:
  web:
    image: rabbit-hole-3-web:1.0
    build: .
    ports:
      - 8000:8000
    env_file:
      - path: .env
        required: true
    networks:
      - postgres-network
    volumes:
      - ./api:/api
  database:
    image: 'postgres:17.4-alpine3.21'
    ports:
      - 8432:5432
    env_file:
      - path: .env
        required: true
    networks:
      - postgres-network
    volumes:
      - db-data:/var/lib/postgresql/data/

volumes:
  db-data:
  
networks:
  postgres-network:
    driver: bridge