# Generated by Django 5.0.4 on 2025-03-31 03:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("api", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Badge",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=20)),
                ("bg_color", models.CharField(max_length=8)),
                ("description", models.CharField(max_length=250)),
                ("data_uri", models.CharField(max_length=30)),
            ],
            options={
                "verbose_name": "Badge",
                "verbose_name_plural": "Badges",
            },
        ),
        migrations.CreateModel(
            name="SceneRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scene Rating",
                "verbose_name_plural": "Scene Ratings",
            },
        ),
        migrations.CreateModel(
            name="UserRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Rating",
                "verbose_name_plural": "User Ratings",
            },
        ),
        migrations.CreateModel(
            name="Scene",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("creator_name", models.CharField(max_length=20)),
                ("title", models.CharField(max_length=30)),
                ("description", models.CharField(max_length=1000)),
                ("gifId", models.CharField(max_length=32)),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("likes", models.IntegerField(default=0)),
                ("dislikes", models.IntegerField(default=0)),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (10, "HIDDEN"),
                            (20, "AWAITING_REVIEW"),
                            (30, "PUBLIC"),
                        ]
                    ),
                ),
                (
                    "badges",
                    models.ManyToManyField(
                        blank=True, related_name="scenes", to="api.badge"
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scenes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="api.scene",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scene",
                "verbose_name_plural": "Scenes",
            },
        ),
    ]
