# Generated by Django 5.0.4 on 2025-03-31 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="badge",
            name="data_uri",
            field=models.CharField(max_length=10000),
        ),
    ]
