# Generated by Django 5.0.4 on 2025-03-31 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_badge_data_uri"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scene",
            name="title",
            field=models.CharField(max_length=40),
        ),
    ]
