# Generated by Django 5.0.4 on 2025-03-31 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_scene_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scene",
            name="description",
            field=models.CharField(max_length=1500),
        ),
    ]
