# Generated by Django 5.0.4 on 2025-03-31 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_scene_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scene",
            name="description",
            field=models.CharField(max_length=1600),
        ),
    ]
