# Generated by Django 5.0.4 on 2025-03-31 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userauth", "0001_initial"),
    ]

    operations = []
