# Generated by Django 5.0.4 on 2025-07-02 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userauth", "0002_auto_20250330_2350"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_received_email",
            field=models.DateTimeField(null=True),
        ),
    ]
