# Generated by Django 5.0.4 on 2025-07-02 16:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userauth", "0003_user_last_received_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expires_at", models.DateTimeField()),
                ("token", models.CharField(max_length=16, unique=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Token",
                "verbose_name_plural": "User Tokens",
                "indexes": [
                    models.Index(fields=["token"], name="userauth_us_token_b41fc1_idx"),
                    models.Index(
                        fields=["expires_at"], name="userauth_us_expires_0af317_idx"
                    ),
                ],
            },
        ),
    ]
