# Generated by Django 5.0.4 on 2025-07-02 17:28

import userauth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userauth", "0004_usertoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usertoken",
            name="token",
            field=models.CharField(
                default=userauth.models.generate_safe_token,
                max_length=16,
                unique=True,
            ),
        ),
    ]
